In [1]:
import torch

In [5]:
x = torch.empty(4,2)
print(x)

tensor([[2.4009e+01, 1.6171e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [6]:
x = torch.rand(4,2)
print(x)

tensor([[0.0952, 0.7677],
        [0.4274, 0.2729],
        [0.8436, 0.8098],
        [0.7953, 0.7689]])


In [7]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [8]:
x = torch.tensor([3,2.3])
print(x)

tensor([3.0000, 2.3000])


In [9]:
x = x.new_ones(2,4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.6955, 0.8201, 0.9861, 0.8973],
        [0.2380, 0.7532, 0.4244, 0.2597]])


In [11]:
print(x.size())

torch.Size([2, 4])


In [14]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [15]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [16]:
it = torch.IntTensor([1,2,3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [17]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [18]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.6960])
1.6959571838378906
torch.float32


In [20]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [21]:
y = torch.ones_like(x, device=device)
print(y)

x = x.to(device)
print(x)
z = x+y
print(z)
print(z.to('cpu', torch.double))

tensor([1.], device='cuda:0')
tensor([1.6960], device='cuda:0')
tensor([2.6960], device='cuda:0')
tensor([2.6960], dtype=torch.float64)


In [22]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [23]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [24]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [25]:
t3 = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                   [[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                   [[1,2,3],
                   [4,5,6],
                   [7,8,9]]])

print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [26]:
import math

In [27]:
a = torch.rand(1,2)*2-1
print(a)

tensor([[-0.9701,  0.3007]])


In [28]:
print(torch.abs(a)) # 절대값
print(torch.ceil(a)) 
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) # a의 값을 -0.5 ~ 0.5 사이로 스케일링

tensor([[0.9701, 0.3007]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.3007]])


In [30]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,2]))) # 중복 제거

tensor([[-0.9701,  0.3007]])
tensor(-0.9701)
tensor(0.3007)
tensor(-0.3347)
tensor(0.8986)
tensor(-0.2917)
tensor([1, 2, 3])


In [31]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.7625, 0.0231],
        [0.0139, 0.0602]])
torch.return_types.max(
values=tensor([0.7625, 0.0602]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([0.7625, 0.0602]),
indices=tensor([0, 1]))


In [32]:
print(x.min(dim=0))
print(x.min(dim=1))

torch.return_types.min(
values=tensor([0.0139, 0.0231]),
indices=tensor([1, 0]))
torch.return_types.min(
values=tensor([0.0231, 0.0139]),
indices=tensor([1, 0]))


In [33]:
x=torch.rand(2,2)
print(x)
y=torch.rand(2,2)
print(y)

tensor([[0.0821, 0.1670],
        [0.3429, 0.3882]])
tensor([[0.0559, 0.3859],
        [0.4405, 0.3596]])


In [34]:
print(torch.add(x,y))

tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])


In [35]:
result = torch.empty(2,4)
torch.add(x,y, out=result)
print(result)

tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])


C:\Users\jjong\AppData\Local\Temp\ipykernel_26716\2982148854.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Resize.cpp:35.)
  torch.add(x,y, out=result)


In [36]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.0821, 0.1670],
        [0.3429, 0.3882]])
tensor([[0.0559, 0.3859],
        [0.4405, 0.3596]])
tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])


In [37]:
print(x)
print(y)
print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.0821, 0.1670],
        [0.3429, 0.3882]])
tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])
tensor([[-0.0559, -0.3859],
        [-0.4405, -0.3596]])
tensor([[-0.0559, -0.3859],
        [-0.4405, -0.3596]])
tensor([[-0.0559, -0.3859],
        [-0.4405, -0.3596]])


In [38]:
print(x)
print(y)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[0.0821, 0.1670],
        [0.3429, 0.3882]])
tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])
tensor([[0.0113, 0.0924],
        [0.2686, 0.2903]])
tensor([[0.0113, 0.0924],
        [0.2686, 0.2903]])
tensor([[0.0113, 0.0924],
        [0.2686, 0.2903]])


In [39]:
print(x)
print(y)
print(x/y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.0821, 0.1670],
        [0.3429, 0.3882]])
tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])
tensor([[0.5950, 0.3021],
        [0.4377, 0.5191]])
tensor([[0.5950, 0.3021],
        [0.4377, 0.5191]])
tensor([[0.5950, 0.3021],
        [0.4377, 0.5191]])


In [40]:
print(x)
print(y)
z= torch.matmul(x,y)
print(z)
print(torch.svd(z))

tensor([[0.0821, 0.1670],
        [0.3429, 0.3882]])
tensor([[0.1380, 0.5529],
        [0.7834, 0.7478]])
tensor([[0.1422, 0.1703],
        [0.3514, 0.4799]])
torch.return_types.svd(
U=tensor([[-0.3491, -0.9371],
        [-0.9371,  0.3491]]),
S=tensor([0.6347, 0.0132]),
V=tensor([[-0.5971, -0.8022],
        [-0.8022,  0.5971]]))


In [41]:
x = torch.Tensor([[1,2],
                  [3,4]])
print(x)
print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

print(x[:, 0])
print(x[:, 1])

print(x[0, :])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


In [42]:
x = torch.randn(4,5)
print(x)

tensor([[ 0.3552,  0.1114,  0.3342,  0.9763,  0.5557],
        [-0.0753,  1.0312,  2.0856, -0.9275,  0.3215],
        [-0.1255, -1.4509,  0.1290,  0.9154,  0.1713],
        [-0.4012,  0.8189, -0.2313,  0.9402,  1.3190]])


In [44]:
y = x.view(20)
print(y)

tensor([ 0.3552,  0.1114,  0.3342,  0.9763,  0.5557, -0.0753,  1.0312,  2.0856,
        -0.9275,  0.3215, -0.1255, -1.4509,  0.1290,  0.9154,  0.1713, -0.4012,
         0.8189, -0.2313,  0.9402,  1.3190])


In [45]:
z = x.view(5, -1) # -1 : 나머지는 알아서 하라는 의미미
print(z)

tensor([[ 0.3552,  0.1114,  0.3342,  0.9763],
        [ 0.5557, -0.0753,  1.0312,  2.0856],
        [-0.9275,  0.3215, -0.1255, -1.4509],
        [ 0.1290,  0.9154,  0.1713, -0.4012],
        [ 0.8189, -0.2313,  0.9402,  1.3190]])


In [49]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.2903])
0.2902970314025879
torch.float32


In [50]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.8806, 0.1016, 0.9165],
         [0.9259, 0.8961, 0.3909],
         [0.7515, 0.4127, 0.8357]]])
torch.Size([1, 3, 3])


In [51]:
t = tensor.squeeze()
print(t)
print(t.shape)


tensor([[0.8806, 0.1016, 0.9165],
        [0.9259, 0.8961, 0.3909],
        [0.7515, 0.4127, 0.8357]])
torch.Size([3, 3])


In [52]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.9601, 0.5895, 0.5037],
        [0.0861, 0.3489, 0.6524],
        [0.7424, 0.2956, 0.8297]])
torch.Size([3, 3])


In [53]:
tensor = t.unsqueeze(dim=0) # 첫번째 차원(dim=0)을 기준으로 차원을 늘림
print(tensor)
print(tensor.shape)

tensor([[[0.9601, 0.5895, 0.5037],
         [0.0861, 0.3489, 0.6524],
         [0.7424, 0.2956, 0.8297]]])
torch.Size([1, 3, 3])


In [54]:
tensor = t.unsqueeze(dim=2) # 세번째 차원(dim=2)을 기준으로 차원을 늘림
print(tensor)
print(tensor.shape)

tensor([[[0.9601],
         [0.5895],
         [0.5037]],

        [[0.0861],
         [0.3489],
         [0.6524]],

        [[0.7424],
         [0.2956],
         [0.8297]]])
torch.Size([3, 3, 1])


In [55]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3,6])
print(z)

print(torch.stack([x,y,z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [56]:
a = torch.randn(1,3,3)
print(a)
b=torch.randn(1,3,3)
print(b)
c=torch.cat((a,b), dim=0)
print(c)
print(c.size())

tensor([[[-0.3327, -0.5516,  0.4599],
         [ 0.3180, -1.6556,  1.2033],
         [-0.4707, -0.6726, -0.5905]]])
tensor([[[-0.4050, -0.0956,  0.0775],
         [ 0.1231,  0.8187, -0.1040],
         [ 1.2102,  0.5528, -0.5515]]])
tensor([[[-0.3327, -0.5516,  0.4599],
         [ 0.3180, -1.6556,  1.2033],
         [-0.4707, -0.6726, -0.5905]],

        [[-0.4050, -0.0956,  0.0775],
         [ 0.1231,  0.8187, -0.1040],
         [ 1.2102,  0.5528, -0.5515]]])
torch.Size([2, 3, 3])


In [57]:
c=torch.cat((a,b), dim=1)
print(c)
print(c.size())

tensor([[[-0.3327, -0.5516,  0.4599],
         [ 0.3180, -1.6556,  1.2033],
         [-0.4707, -0.6726, -0.5905],
         [-0.4050, -0.0956,  0.0775],
         [ 0.1231,  0.8187, -0.1040],
         [ 1.2102,  0.5528, -0.5515]]])
torch.Size([1, 6, 3])


In [58]:
c=torch.cat((a,b), dim=2)
print(c)
print(c.size())

tensor([[[-0.3327, -0.5516,  0.4599, -0.4050, -0.0956,  0.0775],
         [ 0.3180, -1.6556,  1.2033,  0.1231,  0.8187, -0.1040],
         [-0.4707, -0.6726, -0.5905,  1.2102,  0.5528, -0.5515]]])
torch.Size([1, 3, 6])


In [63]:
tensor = torch.rand(4,6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim=1)
print(t1)
print(t2)

tensor([[0.9791, 0.4741, 0.6473, 0.5294, 0.7285, 0.8763],
        [0.3318, 0.1018, 0.4189, 0.2183, 0.9732, 0.5814],
        [0.3475, 0.8663, 0.7313, 0.0754, 0.5162, 0.5242],
        [0.8571, 0.8887, 0.1337, 0.5136, 0.6388, 0.5130]])
tensor([[0.9791, 0.4741],
        [0.3318, 0.1018],
        [0.3475, 0.8663],
        [0.8571, 0.8887]])
tensor([[0.6473, 0.5294],
        [0.4189, 0.2183],
        [0.7313, 0.0754],
        [0.1337, 0.5136]])


In [65]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1)
print(tensor)
print(t1)
print(t2)

tensor([[0.9517, 0.8751, 0.1557, 0.5818, 0.6179, 0.7744],
        [0.9409, 0.5360, 0.0843, 0.2034, 0.2609, 0.3454],
        [0.0107, 0.3365, 0.5918, 0.9065, 0.8989, 0.9607]])
tensor([[0.9517, 0.8751, 0.1557],
        [0.9409, 0.5360, 0.0843],
        [0.0107, 0.3365, 0.5918]])
tensor([[0.5818, 0.6179, 0.7744],
        [0.2034, 0.2609, 0.3454],
        [0.9065, 0.8989, 0.9607]])


In [66]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [67]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [68]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [69]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


#### AutoGrade (자동미분)

In [70]:
a = torch.randn(3,3)
a = a*3
print(a)
print(a.requires_grad)

tensor([[-0.4390,  0.5501,  3.7345],
        [-0.1464, -4.1999, -1.3505],
        [-2.0067,  4.2650,  2.8033]])
False


In [71]:
a.requires_grad_(True) 
print(a.requires_grad)

b = (a*a).sum()
print(b)
print(b.grad_fn)

True
tensor(64.0028, grad_fn=<SumBackward0>)


##### Gradient (기울기)

In [72]:
x = torch.ones(3,3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [73]:
y = x+5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [74]:
z = y*y
out = z.mean()
print(z, out)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


In [75]:
print(out)
out.backward()

tensor(36., grad_fn=<MeanBackward0>)


In [76]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [84]:
x = torch.randn(3, requires_grad=True)

y = x*2

while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([-370.5100, 1433.3209, -609.0751], grad_fn=<MulBackward0>)


In [85]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


##### with torch.no_grad() 를 사용하여 기울기의 업데이트를 하지 않음.

- 기록을 추적하는 것을 방지하기 위해 코드 블럭을 **<span style="color:skyblue">with torch.no_grad()로 감싸면 기울기 계산은 필요없지만, requires_grad=True로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용함</span>**

In [87]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [88]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [89]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [90]:
a = torch.ones(2,2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [91]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
None
None


In [93]:
b = a+2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [94]:
c = b**2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [95]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [96]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


In [97]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [98]:
print(b.data)
print(b.grad)
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
None


C:\Users\jjong\AppData\Local\Temp\ipykernel_26716\2485455394.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print(b.grad)


In [99]:
print(c.data)
print(c.grad)
print(c.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


C:\Users\jjong\AppData\Local\Temp\ipykernel_26716\3875808255.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print(c.grad)


In [100]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None


C:\Users\jjong\AppData\Local\Temp\ipykernel_26716\578081240.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print(out.grad)
